### ISSUE TITLE
[BUG] 混淆方法被调用处不会修改方法名

### ISSUE THREAD

**Issue by KANAZAWA1** [jar-analyzer/jar-obfuscator#6]
[x] java.lang.NoClassDefFoundError: gadget/xxxxxx
师傅，我的gadget/xxxxxx类是被 jar-obfuscator混淆过的（应为it1il/i1il类），但是其他类我没混淆，其他类会去调用这个我混淆过的类，还用的是混淆前的类名gadget/xxxxxx去调用的（而不是it1il/i1il类），导致java.lang.NoClassDefFoundError报错。
这种我需要怎么设置配置文件才会将他这种问题解决呢？

**Comment by 4ra1n** [comment]
一个临时的简单方案是：

以下的混淆不修改引用，如遇 BUG 可以搭配使用这些配置
- 开启 enableEncryptString 和 enableAdvanceString 加密字符串
- 开启 enableJunk 花指令混淆
- 开启 enableXOR 对数字进行异或加密

具体原因等我再排查一下

**Comment by 4ra1n** [comment]
master 分支最新的代码我测试

```yaml
obfuscatePackage: [ me.n1ar4.fake.gadget ]
rootPackages: [ me.n1ar4 ]
```

我的配置是

```yaml
enableClassName: true
enablePackageName: true
enableMethodName: false
enableFieldName: true
enableParamName: true
```

例如这个配置，我观察到结果是 gadget  包下所有类都混淆了且 me.n1ar4 中所有类的引用都改了，可以正常使用

这个问题应该是 enableMethodName 的 BUG 不对方法名进行混淆的话，其他功能测试可以
